### ISSUE TITLE
Feature Request: Day/Night cycle

### ISSUE THREAD

**Issue by xxsnowy92xx** [ScreteMonge/3D-Weather#17]
A toggleable day/night cycle would be completely next level.
Maybe if not apart of this plug-in, but a new one?
I made a github account JUST to suggest this.
The weather plug-in blew me away and figured ScreteMonge would be my best bet for a plug-in suggestion!

**Comment by ScreteMonge** [comment]
Sorry for the late response.

I'm glad you enjoy the plugin! I'll have you know that 117HD is working on a day/night cycle already and they'll do it far, far better than myself.

It'd be nice to have a day/night cycle outside of 117, but the problem in my view is that it would just make everything darker and that wouldn't be good enough. Part of the beautiful thing about night irl is that we have lights that contrast the darkness (moon, stars, manmade lights) - you wouldn't have that unless you introduced a proper lighting system to the game. It's convenient for 117 because they've already created such a lighting system.

So the short of it: probably not from me, but 117 is making progress there!
