### ISSUE TITLE
Dynamic seasons not affecting HD117 Seasons

### ISSUE THREAD

**Issue by hobiewetzels** [ScreteMonge/3D-Weather#28]
Hi, great plug-in!

It does not seem to override the automatic seasons set bij HD117. So they still have priority over the 7 day cycle from your plug-in. 

Also it would be great if the skybox could be changed dynamically instead of the skybox from the HD117 season. 

Also would be amazing if it was possible to add night/day cycles by adjusting the 117HD brightness/saturation settings dynamically. 

Loving everything else!

**Comment by ScreteMonge** [comment]
If you set the Season in 3D Weather to 117HD, it'll use 117's season. If you set the Season in 3D Weather to Dynamic, it should follow it's own course (which may or may not happen to align with 117 - at this time of writing, 117's Automatic season should be Winter and 3D Weather's Dynamic season should be Summer). Let me know if that isn't working for you.

I've covered skybox changes in Issue #25. Short answer is that the skybox is too much work at this time, possibly in the future though.

Night/Day I'm leaving for another plugin entirely. 117 is planning their own from what I know. It's also just not good practice to automatically adjust 117's config through my own plugin - that can get really messy and disorganized quickly.

Thanks for the suggestions!

**Comment by hobiewetzels** [comment]
Ah thanks for the clear up. Makes sense! 

I have my settings with 3D weather set to: season type = dynamic and 117 seasonal theme = automatic. This always defaults to winter for me. 

If I change the 117HD season to summer or autumn it will change to that season. Whenever I change the 3D weather season to anything else nothing changes. So it seems to always take the 117HD setting. Any idea on how to fix? Already re-installed both plugins.

**Comment by ScreteMonge** [comment]
I think I get where you're getting confused.

3D Weather can't change anything about 117's settings or season. 3D Weather's overlay will indicate what 3DW's current season is, not 117's season. Further, 3DW only affects what weathers can occur, while 117's season will determine the rest of the in-game environment (like whether there's snow on the ground, or the leaves on trees are red/orange/yellow).

What you'll want to do is change 117's season in that plugin's config menu if you want the in-world environment to change. See the attached image.

![image](https://github.com/ScreteMonge/3D-Weather/assets/107197518/7aa12179-2b1e-4dcf-968e-b46d7438d0c1)

Now, while 3DW can't affect 117's season, you can set 3DW's season to "117HD" instead of Dynamic. Therefore, whenever you change 117's season, 3DW will follow.
