### ISSUE TITLE
Feature request: Tie ambiance volume to ingame audio controls

### ISSUE THREAD

**Issue by Hibbs6** [ScreteMonge/3D-Weather#9]
I think it's pretty unwieldy to have to adjust the volume for the ambiance via the plugin settings. If possible, tying it to the existing volume knobs or ideally even adding a separate knob in that menu would be amazing.

**Comment by ScreteMonge** [comment]
I definitely wouldn't want to tie it to an existing knob so that players can maintain independent control of the separate sound types and I'd have to perfectly balance the tracks with those relevant sounds. An additional slider would be nice, assuming I can push around the other menu elements without trouble. I'll look into it

**Comment by samsteele** [comment]
I agree that I would like the ambient weather sounds to be tied to the in-game area sounds slider

**Comment by ScreteMonge** [comment]
Now possible thank to a toggle in the config menu
